// react/src/components/Index.js
import React from 'react'
import Head from './index/Head'
import Nav from './index/Nav'
import MyRouter from '../router/MyRouter'
import IndexRoutes from '../router/IndexRoutes'

export default class Index extends React.Component{

    render(){
        return (<div id="index">
            <Head></Head>
            <Nav></Nav>
            <section><MyRouter routes={IndexRoutes}></MyRouter></section>
        </div>)
    }
}

// vue/src/components/Index.vue
<template>
  <div id="index">
    <Head></Head>
    <Nav></Nav>
    <section>
      <router-view></router-view>
    </section>
  </div>
</template>

<script>
import Head from './index/Head'
import Nav from './index/Nav'
export default {
  components:{Head,Nav}
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
</style>
