// react/src/components/Songlist.js
import React from 'react'
import {withRouter} from 'react-router-dom'
// 参数：arr:{id,name,artists,songname}, showNum

class Songlist extends React.Component{
    static defaultProps={
        showNum:false
    }
    jump(id){
        this.props.history.push('/play/'+id)
    }
    render(){
        return (<ul className="news">
            {
                this.props.arr.map((item,i)=>{
                    return (<li onClick={this.jump.bind(this,item.id)} key={item.id} className="item">
                        {
                            (()=>{
                                if(this.props.showNum){
                                    return (<div className="num">{i > 8 ? i + 1 : '0' + (i + 1)}</div>)
                                }
                            })()
                        }
                        <div className="left">
                            <p className="name">{item.name}</p>
                            <p className="info">
                                <span className="quality"></span>
                                {
                                    (()=>{
                                        let arr = item.artists.map(item=>{
                                            return item.name
                                        });
                                        return arr.join('、')
                                    })()
                                }-{item.songName}
                            </p>
                        </div>
                        <span className="right iconfont icon-playcircle"></span>
                    </li>)
                })
            }
        </ul>)
    }
}

export default withRouter(Songlist)

// vue/src/components/Songlist.vue
// 参数：arr:{id,name,artists,songname}, showNum
<template>
  <ul class="news">
    <li v-for="(item,i) in arr" :key="item.id" class="item" @click="jumpPlay(item.id)">
      <div v-if="showNum" class="num">{{i > 8 ? i + 1 : '0' + (i + 1)}}</div>
      <div class="left">
        <p class="name">{{item.name}}</p>
        <p class="info">
          <span class="quality"></span>
          {{showAr(item.artists)}}-{{item.songName}}
        </p>
      </div>
      <span class="right iconfont icon-playcircle"></span>

    </li>
  </ul>
</template>

<script>
export default {
  props: ["arr", "showNum"],
  created() {},
  methods:{
    jumpPlay(id){
      this.$router.push('/play/'+id)
    },
    showAr(ar){
      let arr =  ar.map(item=>{
        return item.name
      })
      return arr.join(',')
    }
  }

};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
</style>
