// vue/src/components/index/Search.vue
<template>
  <div id="search">
    <div class="search-box">
      <span class="iconfont icon-sousuo"></span>
      <input ref="inp" type="text" v-model="ser" @keyup.enter="search" />
    </div>
    <ul class="clear" v-if="isSer">
      <li class="key-word" v-for="(item,index) in arr" :key="index" @click="choose(item)">{{item}}</li>
    </ul>
    <SongList :arr="songlist" :showNum="false"></SongList>
  </div>
</template>
<script>
import SongList from "../Songlist";
export default {
  components: { SongList },
  data() {
    return {
      arr: [],
      ser: "",
      chooose: null,
      songlist: []
    };
  },
  watch: {
    ser(i) {
      if (i == "") {
        this.songlist = [];
      }
    }
  },
  created() {
    //   改变nav样式
    this.$bus.$emit("link", 2);
    // 获取关键词
    this.$axios.get(this.$api.searchKeyWord).then(res => {
      this.arr = res.data.result.hots.map(item => {
        return item.first;
      });
    });
  },
  computed: {
    isSer() {
      if (this.ser === "") {
        return true;
      } else {
        return false;
      }
    }
  },
  methods: {
    choose(val) {
      this.ser = val;
      this.$refs.inp.focus();
    },
    search() {
      if (this.ser != "") {
        this.$axios
          .get(this.$api.search + "?keywords=" + this.ser)
          .then(res => {
            this.songlist = res.data.result.songs.map(item => {
              return {
                id: item.id,
                name: item.name,
                artists: item.artists,
                songName: item.album.name
              };
            });
          });
      }
    }
  }
};
</script>

// react/src/components/index/Search.js
import React from 'react'
import SongList from '../Songlist'

class Search extends React.Component{
    constructor(){
        super()
        this.state={
            arr:[],
            ser:'',
            chooose:null,
            songlist:[]
        }
    }
    componentDidMount(){
        this.$axios.get(this.$api.searchKeyWord)
        .then(res=>{
            // console.log(res.data.result.hots)
            let arr = res.data.result.hots.map(item=>{
                return item.first
            })
            this.setState({
                arr
            })
        })
    }
    change(e){
        this.setState({
            ser:e.target.value
        })
    }
    choose(index){
        let ser = this.state.arr[index]
        this.setState({
            ser
        })
        this.refs.search.focus();
    }
    search(e){
        if(e.keyCode===13 && this.state.ser!=''){
            this.$axios.get(this.$api.search+'?keywords='+this.state.ser)
            .then(res=>{
                this.setState({
                    songlist:res.data.result.songs
                })
            })
        }
    }
    render(){
        let arr = this.state.songlist.map(item=>{
            return {
                id:item.id,
                name:item.name,
                artists:item.artists,
                songName:item.album.name
            }
        })
        return (<div id="search">
            <div className="search-box">
                <span className="iconfont icon-sousuo"></span>
                <input type="text" value={this.state.ser} ref='search' onChange={this.change.bind(this)} onKeyUp={this.search.bind(this)}/>
            </div>
            <ul className="clear ">
                {
                    (()=>{
                        
                        if(this.state.ser===''){
                            return  this.state.arr.map((item,index)=>{
                                return (<li key={index} className="key-word" onClick={this.choose.bind(this,index)}>{item}</li>)
                            })
                        }
                    })()
                    
                }
            </ul>
            <SongList arr={arr}></SongList>
        </div>)
    }
}

export default Search
