// vue/src/components/Play.vue
<template>
  <div id="play" v-if="show">
    <audio :src="musicUrl" ref="audio" @timeupdate='update()'></audio>
    <div class="head">
      <span @click="back" class="back iconfont icon-backicon1"></span>
      <img
        :style="{ transform: paused ? 'rotate(0deg)' : 'rotate(20deg)' }"
        class="needle"
        src="../images/play/needle-ip6.png"
        alt
      />
      <div class="cd" @click="play">
        <img :src="song.al.picUrl" alt />
        <span :style="{ display: paused ? 'block' : 'none' }" class="iconfont icon-playcircle"></span>
      </div>
    </div>
    <div class="content">
      <p class="title">
        <span class="songname">{{song.name}}</span>
        -{{songAr(song.ar)}}
      </p>
      <ul class="lyric" ref="box">
        <li
          v-for="item in lyricArr"
          :key="item[0]"
        >
        <div v-if='item[0]===playtime' ref='myref'>{{item[1]}}</div>
        <span v-else>{{item[1]}}</span>
        </li>
      </ul>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      paused: true,
      song: {},
      show: false,
      musicUrl: "",
      lyric: null,
      lyricArr: [],
      playtime: "00:00"
    };
  },
  created() {
    let id = this.$route.params.id;
    this.$axios
      .all(
        this.getData([
          this.$api.songdetail + "?ids=" + id,
          this.$api.musicUrl + "?id=" + id,
          this.$api.lyric + "?id=" + id
        ])
      )
      .then(res => {
        let song = res[0].data.songs[0];
        let url = res[1].data.data[0].url;
        let lyricData = res[2].data.lrc.lyric;
        let reg = /\[(.*)](.*)/g;
        let lyric = {};
        lyricData.replace(reg, (a, b, c) => {
          lyric[b.slice(0, 5)] = c;
        });
        this.song = song;
        this.show = true;
        this.musicUrl = url;
        this.lyric = lyric;
        this.lyricArr = Object.entries(lyric);
      });

    // audio.ontimeupdate = ()=>{
    //   let t = this.timeChange(audio.currentTime);
    //   console.log(t)
    // }
    // audio.ontimeupdate = () => {
    //   // console.log(audio.currentTime)
    //   let t = this.timeChange(audio.currentTime);
    //   if (t in this.state.lyric) {
    //     this.setState(
    //       {
    //         playtime: t
    //       },
    //       () => {
    //         let box = this.refs.box;
    //         let target = this.myref;
    //         box.scrollTop = target.offsetTop;
    //         // if (target.offsetTop > 50) {
    //         //   $(box).animate(
    //         //     {
    //         //       scrollTop: target.offsetTop - 50
    //         //     },
    //         //     500
    //         //   );
    //         // }
    //       }
    //     );
    //   }
    // };
  },
  mounted(){

  },
  methods: {
    update(){
      let audio = this.$refs.audio
      // console.log(audio)
      let t = this.timeChange(audio.currentTime);
      if(t in this.lyric){
        console.log(1)
        this.playtime = t;
        let box = this.$refs.box;
        let target = this.$refs.myref[0];
        console.log(target.previousElementSibling)
        target.className = 'active'
        box.scrollTop = target.offsetTop;
      }
    },
    getData(arr) {
      return arr.map(item => {
        return this.$axios.get(item);
      });
    },
    timeChange(t) {
      let m = Math.floor(t / 60)
          .toString()
          .padStart(2, "0"),
        s = Math.floor(t % 60)
          .toString()
          .padStart(2, "0");
      return m + ":" + s;
    },
    back() {
      this.$router.go(-1);
    },
    play() {
      console.log(this.$refs.audio);
      // let audio = this.$refs.audio
      this.paused = !this.paused;
      let audio = this.$refs.audio;
      if (this.paused) {
        audio.pause();
      } else {
        audio.play();
      }
    },
    songAr(ar) {
      let arr = ar.map(item => {
        return item.name;
      });
      return arr.join("、");
    }
  }
};
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
</style>

// react/src/components/Play.js
import React from 'react'
import $ from 'jquery'

export default class Play extends React.Component {
    constructor() {
        super()
        this.state = {
            paused: true,
            song: {},
            show:false,
            musicUrl:'',
            lyric:null,
            playtime:'00:00'
        }
    }
    componentDidMount() {
        let id = this.props.match.params.id;
        // console.log(id)
        this.$axios.all(this.getData([
            this.$api.songdetail + '?ids=' + id,
            this.$api.musicUrl + '?id=' + id,
            this.$api.lyric + '?id=' + id
        ])).then(res => {
            let song = res[0].data.songs[0]
            let url = res[1].data.data[0].url;
            let lyricData = res[2].data.lrc.lyric
            // console.log(lyric)
            let reg = /\[(.*)](.*)/g
            let lyric = {};
            lyricData.replace(reg,(a,b,c)=>{
                lyric[b.slice(0,5)]=c
            })
            // console.log(lyric)
            this.setState({
                song,
                show:true,
                musicUrl:url,
                lyric
            },()=>{
                let audio = this.refs.audio;
                audio.ontimeupdate=()=>{
                    // console.log(audio.currentTime)
                    let t = this.timeChange(audio.currentTime);
                    if(t in this.state.lyric){
                        this.setState({
                            playtime:t
                        },()=>{
                            let box = this.refs.box
                            let target = this.myref
                            // box.scrollTop = target.offsetTop;
                            if(target.offsetTop>50){
                                $(box).animate({
                                    scrollTop:target.offsetTop-50
                                },500)
                            }
                        })
                    }
                    
                    
                }
            })
        })
    }
    getData = arr => {
        return arr.map(item => {
            return this.$axios.get(item)
        })
    }
    timeChange(t){
        let m = (Math.floor(t/60).toString()).padStart(2,'0'), s = Math.floor(t%60).toString().padStart(2,'0');
        return m+':'+s
    }
    play() {
        let p = !this.state.paused;
        this.setState({
            paused: p
        })
        // console.log(this.refs.audio.currentTime)
        let audio = this.refs.audio;
        if(!p){
            audio.play()
        }else{
            audio.pause()
        }
    }
    back(){
        this.props.history.go(-1)
    }
    render() {
        let { paused, song,show,musicUrl,lyric,playtime } = this.state
        if (show) {
            return (<div id="play">
                <audio src={musicUrl} ref="audio"></audio>
                <div className="head">
                    <span onClick={this.back.bind(this)} className="back iconfont icon-backicon1"></span>
                    <img style={{ transform: paused ? 'rotate(0deg)' : 'rotate(20deg)' }} className="needle" src={require('../images/play/needle-ip6.png')} alt="" />
                    <div className="cd" onClick={this.play.bind(this)}>
                        <img src={song.al.picUrl} alt="" />
                        <span style={{ display: paused ? 'block' : 'none' }} className="iconfont icon-playcircle"></span>
                    </div>
                </div>
                <div className='content'>
                    <p className="title"><span className='songname'>{song.name}</span>-{
                        (() => {
                            if (song.ar) {
                                let arr = song.ar.map(item => { return item.name })
                                return arr.join('、')
                            }
                        
                        })()
                    }</p>
                    <ul className="lyric" ref="box">
                        {
                            Object.entries(lyric).map((item)=>{
                                return (<li key={item[0]} className={item[0]===playtime?'active':''} ref={(ele)=>{if(item[0]===playtime){this.myref=ele}}}>{item[1]}</li>)
                            })
                        }
                    </ul>
                </div>
            </div>)
        }else{
            return(<></>)
        }
    }
}
